#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Azure Container Apps Setup Wizard
# =============================================================================
#
# Deploys infra/main.bicep and handles the things Bicep can't:
#   - Resource provider registration
#   - Service principal creation
#   - GitHub Actions secret setup
#
# Saves selections to .setup-aca.env so re-runs pre-fill previous values.
# The Bicep deployment is idempotent — safe to re-run.
#
# Prerequisites:
#   - az CLI installed and logged in (az login)
#   - gh CLI installed and logged in (gh auth login)
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BICEP_FILE="${SCRIPT_DIR}/../infra/main.bicep"
CONFIG_FILE=".setup-aca.env"

echo ""
echo "=== Azure Container Apps Setup Wizard ==="
echo ""
echo "This script will:"
echo "  1. Register required Azure resource providers"
echo "  2. Create a resource group"
echo "  3. Deploy Container Apps infrastructure (Bicep)"
echo "  4. Create a service principal for GitHub Actions"
echo "  5. Set the AZURE_CREDENTIALS secret in GitHub"
echo ""
echo "Prerequisites: az CLI logged in, gh CLI logged in"
echo ""

# ---- Preflight checks -------------------------------------------------------

if ! command -v az &> /dev/null; then
  echo "Error: az CLI not found. Install it: https://aka.ms/install-azure-cli"
  exit 1
fi

if ! command -v gh &> /dev/null; then
  echo "Error: gh CLI not found. Install it: https://cli.github.com"
  exit 1
fi

if ! az account show &> /dev/null; then
  echo "Error: Not logged in to Azure. Run: az login"
  exit 1
fi

if ! gh auth status &> /dev/null; then
  echo "Error: Not logged in to GitHub CLI. Run: gh auth login"
  exit 1
fi

if [[ ! -f "$BICEP_FILE" ]]; then
  echo "Error: Bicep template not found at ${BICEP_FILE}"
  exit 1
fi

# ---- Load saved config (if any) ---------------------------------------------

if [[ -f "$CONFIG_FILE" ]]; then
  echo "Loading saved config from ${CONFIG_FILE}"
  echo ""
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
fi

# ---- Derive defaults from environment ---------------------------------------

DEFAULT_REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "")
DEFAULT_REPO_NAME=$(echo "$DEFAULT_REPO" | cut -d'/' -f2)
DEFAULT_IMAGE="ghcr.io/${DEFAULT_REPO}:latest"

# ---- Prompts -----------------------------------------------------------------

prompt() {
  local var_name=$1
  local prompt_text=$2
  local default=$3
  local value

  if [[ -n "$default" ]]; then
    read -rp "${prompt_text} [${default}]: " value
    value="${value:-$default}"
  else
    read -rp "${prompt_text}: " value
    while [[ -z "$value" ]]; do
      echo "  This field is required."
      read -rp "${prompt_text}: " value
    done
  fi

  eval "$var_name=\"$value\""
}

# Saved values override env-derived defaults
prompt APP_NAME       "App name"                    "${SAVED_APP_NAME:-$DEFAULT_REPO_NAME}"
prompt RESOURCE_GROUP "Resource group name"         "${SAVED_RESOURCE_GROUP:-rg-${APP_NAME}}"
prompt LOCATION       "Azure region"                "${SAVED_LOCATION:-westus2}"
prompt IMAGE          "GHCR image"                  "${SAVED_IMAGE:-$DEFAULT_IMAGE}"
prompt TARGET_PORT    "Target port"                 "${SAVED_TARGET_PORT:-3000}"
prompt MIN_REPLICAS   "Min replicas"                "${SAVED_MIN_REPLICAS:-1}"
prompt GITHUB_REPO    "GitHub repo for secrets"     "${SAVED_GITHUB_REPO:-$DEFAULT_REPO}"

# ---- Save selections --------------------------------------------------------

cat > "$CONFIG_FILE" <<CONF
# Auto-generated by setup-aca.sh — safe to edit or delete
SAVED_APP_NAME="${APP_NAME}"
SAVED_RESOURCE_GROUP="${RESOURCE_GROUP}"
SAVED_LOCATION="${LOCATION}"
SAVED_IMAGE="${IMAGE}"
SAVED_TARGET_PORT="${TARGET_PORT}"
SAVED_MIN_REPLICAS="${MIN_REPLICAS}"
SAVED_GITHUB_REPO="${GITHUB_REPO}"
CONF

echo ""
echo "(Saved selections to ${CONFIG_FILE})"

echo ""
echo "=== Configuration Summary ==="
echo "  App name:        ${APP_NAME}"
echo "  Resource group:  ${RESOURCE_GROUP}"
echo "  Region:          ${LOCATION}"
echo "  Image:           ${IMAGE}"
echo "  Target port:     ${TARGET_PORT}"
echo "  Min replicas:    ${MIN_REPLICAS}"
echo "  GitHub repo:     ${GITHUB_REPO}"
echo ""

read -rp "Proceed? (y/N): " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

echo ""

# ---- 1. Resource providers ---------------------------------------------------

echo "--- Registering required resource providers ---"
az provider register -n Microsoft.App --wait
az provider register -n Microsoft.OperationalInsights --wait
echo "Resource providers registered."

# ---- 2. Resource Group -------------------------------------------------------

echo ""
echo "--- Creating resource group: ${RESOURCE_GROUP} ---"
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output table

# ---- 3. Bicep Deployment -----------------------------------------------------

echo ""
echo "--- Deploying infrastructure (Bicep) ---"
DEPLOY_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$BICEP_FILE" \
  --parameters \
    appName="$APP_NAME" \
    image="$IMAGE" \
    targetPort="$TARGET_PORT" \
    minReplicas="$MIN_REPLICAS" \
    location="$LOCATION" \
  --query "properties.outputs" \
  --output json)

FQDN=$(echo "$DEPLOY_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['fqdn']['value'])")

echo "Infrastructure deployed."
echo ""
echo "=== Your app is live at ==="
echo "  https://${FQDN}"

# ---- 4. Service Principal for GitHub Actions ---------------------------------

echo ""
echo "--- Creating service principal for GitHub Actions ---"

SUB_ID=$(az account show --query id -o tsv)
RG_ID="/subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}"

SP_JSON=$(az ad sp create-for-rbac \
  --name "github-actions-${APP_NAME}" \
  --role contributor \
  --scopes "$RG_ID" \
  --sdk-auth)

echo "Service principal created."

# ---- 5. Set GitHub Secret ----------------------------------------------------

echo ""
read -rp "Set AZURE_CREDENTIALS secret in ${GITHUB_REPO}? (y/N): " set_secret
if [[ "${set_secret}" == "y" || "${set_secret}" == "Y" ]]; then
  echo "$SP_JSON" | gh secret set AZURE_CREDENTIALS --repo "$GITHUB_REPO"
  echo "Secret AZURE_CREDENTIALS set in ${GITHUB_REPO}."
else
  echo ""
  echo "=== AZURE_CREDENTIALS value (set this as a GitHub secret) ==="
  echo "$SP_JSON"
fi

# ---- Cloudflare DNS instructions --------------------------------------------

echo ""
echo "=== Cloudflare DNS Setup ==="
echo ""
echo "Your app is live at: ${FQDN}"
echo ""
echo "To use a custom domain with Cloudflare:"
echo "  1. Add a CNAME record pointing to: ${FQDN}"
echo "  2. Set proxy status: Proxied (orange cloud)"
echo "  3. Generate an Origin Certificate (SSL/TLS > Origin Server)"
echo "  4. Upload it to ACA:"
echo "     az containerapp env certificate upload \\"
echo "       --name ${APP_NAME}-env \\"
echo "       --resource-group ${RESOURCE_GROUP} \\"
echo "       --certificate-file <path-to-cert.pem> \\"
echo "       --private-key-file <path-to-key.pem>"
echo "     az containerapp hostname bind \\"
echo "       --name ${APP_NAME} \\"
echo "       --resource-group ${RESOURCE_GROUP} \\"
echo "       --hostname <your-domain> \\"
echo "       --certificate <cert-name>"
echo "  5. Set SSL mode to Full (Strict) in Cloudflare dashboard"
echo ""
echo "=== Setup Complete ==="
