name: Turbo Setup
description: Set up Node.js with cached node_modules, Turbo remote cache, and optional workspace pre-build

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '24'
  pre-build-filter:
    description: 'Turbo filter for packages to build before main task (e.g. @my-org/shared)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore node_modules cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Save node_modules cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}

    - name: Turbo remote cache
      uses: rharkor/caching-for-turbo@v2.2.1

    - name: Pre-build workspace packages
      if: inputs.pre-build-filter != ''
      shell: bash
      run: npx turbo run build --filter=${{ inputs.pre-build-filter }}
